# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a59828d262fd4fa1fee4ef9b2dbc50df1cfa442149a88009738a3879325e71ac23f9d9342cf5051fa9ed9d9370ee50572ee2b3498efab9d6337eacf242d1a09

test:
  secret_key_base: cc658ffd0b290e102eccf37c91cdae097bd9b3b8991dfd29fb48a451b4006ea75976f8477a3a8c87c45c0b222b59a8382e4e87f30a086426776792c798f3a0e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
